version: 2
updates:
  # Monitor Dockerfile for base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "chekkan"
    labels:
      - "dependencies"
      - "docker"

  # Monitor GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "chekkan"
    labels:
      - "dependencies"
      - "github-actions"